### ISSUE TITLE
Navigation: Fehler bei Wechsel in ContestScreen

### ISSUE THREAD

**Issue by ievo** [bespr/SlamScoreBoard#13]
Bei mehreren geladenen Wettbewerben kommt man von ConfigContest Screen oder vom MainConfigure Screen im in den ContestScreen des ersten Wettbewerbs. Das gilt auch für Wechsel aus PausenScreen.

**Comment by bespr** [comment]
Folgendes zwei Fälle konnte ich reproduzieren: 

Fall A:
1. Start auf #configure
2. Klick auf Conf im Contest1 (#contestConf/1)
3. Klick auf ContestScreen (SOLL: #contest/1, IST: #contest/0)

Fall B:
1. Start auf #configure
2. Klick auf Contest1 (#contest/1)
3. Klick auf PausenScreen (#pause)
4. Klick auf ContestScreen (SOLL: #contest/1, IST: #contest/0)
