### ISSUE TITLE
Optimierung auf FullHD und Auflösungseinstellungen

### ISSUE THREAD

**Issue by bespr** [bespr/SlamScoreBoard#14]
Die verbreitesten Auflösungen bei [Digitec-Beamern](https://www.digitec.ch/de/s1/producttype/projektor-84?tagIds=538-539) sind diese
1. FullHD [1920 x 1080]  31%
2. WXGA [1280 x 800]    40%
3. XGA [1024 x 768]     15%
4. Nächstverbreiteste   3%

Ich schlage deshalb vor:
1. Optimierung auf FullHD (defaulteinstellung)
2. Einstellungsmöglichkeit (wird auch in die SSB-Savefiles gespeichert) der drei Auflösungen FullHD, WXGA und XGA. 

Optimierung heisst, dass die an der SM15 eingesetzten Modi, Teilnehmerzahlen, Juryanzahl ein schönes Bild abgeben. Speziellere Modi, die an der SM15 nicht zum Zuge kommen, werden dann ev. irgenwann später dazuoptimiert.

**Comment by ievo** [comment]
Einverstanden.

**Comment by bespr** [comment]
Ich habe das jetzt ein bisschen anders gelöst. Man kann keine Auflösung einstellen. Je kleiner aber der Bildschirm gemacht wird, desto kleiner wird auch die Standardschriftgrösse:
- Bei HD (1920px) bzw. mehr als 1800 Pixel: font-size: 24px; 
- Max. 1800 Pixel: font-size: 22px; 
- Max. 1600 Pixel: font-size: 20px;
- Max. 1400 Pixel: font-size: 18px;
- Max. 1200 Pixel: font-size: 16px;
- Max. 1000 Pixel: font-size: 14px;

Damit ist es quasi auf HD optimiert, kleinere Auflösungen sollten aber auch funktionieren.

Von der Höhe ist es so angepasst, dass es ca. bis 14 Slammer geht, ohne das man scrollen muss. Und ein bisschen Scrollen wäre wohl auch nicht allzu tragisch. Deshalb schliesse ich dieses Issue mal vorläufig.
