### ISSUE TITLE
Kopieren der Slammer in die nächste Runde mittels Drag'n'Drop

### ISSUE THREAD

**Issue by bespr** [bespr/SlamScoreBoard#17]
Im Screen `#contest` sollte es neben jedem Slammer einen versteckten Button haben, der es erlaubt, den Slammer in die nächste Runde zu nehmen.

Zu klären: In welche Gruppe, wenn es in der nächsten Runde mehrere Gruppen gibt?

**Comment by ievo** [comment]
Oft wird der Slammer in den nächsten frei Platz der nächsten Runde genommen unabhängig von der Gruppe (top - down). Ist das umsetzbar?

**Comment by bespr** [comment]
@ievo Das ist nicht möglich, da es so etwas wie einen «_nächsten frei Platz_» nicht gibt. Es gibt lediglich zB zwei Gruppen in der nächsten Runde, und die erste Gruppe würde nach der bisherigen Definition beliebig gefüllt und die zweite Gruppe leer bleiben.

Ansatz A: Ievo's Vorschlag PLUS: Der User müsste pro Gruppe definieren, wieviele Plätze verfügbar sind.

Ansatz B: Anstelle eines Buttons, macht mans doch mit Drag'n'Drop und man muss den Slammer halt in die richtige Gruppe ziehen.

Ich denke, dass Ansatz B besser ist.

**Comment by ievo** [comment]
@bespr Ich gebe dir Recht bespr. Ansatz B ist zu favorisieren.

**Comment by ievo** [comment]
Funktioniert. Getestet mit 3 Runden und vielen 5 Gruppen (total).
