### ISSUE TITLE
Von ContestScreen direkt in SlammerScreen und zurück

### ISSUE THREAD

**Issue by bespr** [bespr/SlamScoreBoard#18]
Im Cupmodus wird der Screen `#contest` sehr wichtig sein. Deshalb sollte man von dort aus auch in den Slammer-Modus und wieder zurück wechseln können, statt jedesmal über den GruppenScreen gehen zu müssen

**Comment by bespr** [comment]
Ich habe das so gelöst: Wenn man im Contest-Screen auf einen Namen klickt (ohne CTRL auch zu drücken natürlich, sonst gäbe es ja eine Markierung), dann wird geschaut, ob man innerhalb der ersten 40 Pixel des Namens geklickt hat.
- Falls ja (Pixel 1 - 40): Zum Slammer-Screen
- Falls nein (Ab Pixel 41): Zum Gruppen-Screen.

Der Grund: Wenn der ganze Slammer mit dem Slammer-Screen verlinkt gewesen wäre (das Slammer-Element geht eben bis ganz nach hinten, nicht nur soweit, wie der Name reicht), dann wäre fast kein Platz mehr für den Gruppen-Screen-Link gewesen. Und einen weiteren Fade-In-Button wollte ich nicht unbedingt machen.

@ievo: In Ordnung so? Dann bitte noch ins Manual übernehmen.

**Comment by ievo** [comment]
Das wäre schon so in Ordnung, wenn es so funktionierte wie beschrieben. Zur Zeit ist es aber so, dass man auch zum Slammer Screen gelangt, wenn man ganz rechts klickt.

Vorschlag: Gibt es auch die Möglichkeit Elemente einzufärben, wenn die Maus darüber bewegt wird? Wenn ja: Gruppen-Element einfärben, wenn Gruppe gewählt wird.

**Comment by bespr** [comment]
@ievo Ich glaube, du lügst. Falls nicht, kannst du mir sagen, in welchem Browser/OS du das festgestellt hast, dass man vom Contest-Screen auch dann in den Slammer-Screen gelangt, wenn man ganz rechts klickt?

Ich habe ein (sehr hässliches) Rechteck eingefügt, das erscheint, wenn man mit der Maus über den Slammer-Namen im Contest-Screen fährt (genauer: über die ersten 20 Pixel des Namens). Wenn man innerhalb dieser 20px-Box auf den Slammer-Namen klickt, sollte man zum Slammer-Screen gelangen. Wenn man ausserhalb dieser 20px-Box auf den Slammer-Namen klickt, sollte man zum Gruppen-Screen gelangen.

Getestet mit Firefox und Chrome auf Ubuntu

**Comment by ievo** [comment]
Es könnte daran gelegen haben, dass ich die 20px am falschen Ort vermutet hatte, bzw. beginnend beim Rahmen. Ich würde statt 20px 50px vorschlagen. Bei den 20px vertippt man sich ständig. Deshalb werde ich diesen issue nochmals an dich zurücksenden.

**Comment by bespr** [comment]
Da hast du natürlich recht. 50 Pixel ist ideal. Jetzt bitte nochmals testen, dann können wir das zumachen.

**Comment by ievo** [comment]
Jetzt bin ich zufrieden. Funktioniert.
