### ISSUE TITLE
Rundenname Leerschlag

### ISSUE THREAD

**Issue by ievo** [bespr/SlamScoreBoard#21]
Es sollte möglich sein, einen Leerschlag bei der Eingabe des Rundennamens zu machen. Dies ist zwar möglich aber nicht an letzter Stelle des Namens. Für die erste Version ist dieser Issue nicht entscheidend.

**Comment by bespr** [comment]
Stimmt! Ist glaub auf dem gleicher Fehler des unfähigen Entwicklers aufgebaut wie schon Issue #7 (Leerschläge bei Slammer-Eingabe)

**Comment by bespr** [comment]
Das sollte nun auch gefixt sein. Wie bei #7 (nun on **blur** statt on **key up**). Anfängerfehler!
