### ISSUE TITLE
Einige Dinge bleiben Default-Orange statt die eingestellte Farbe zu nehmen

### ISSUE THREAD

**Issue by bespr** [bespr/SlamScoreBoard#26]
> schön wäre es, wenn man auch die Rahmenlinienfarbe wählen könnte, weil das sonst manchmal zu seltsamen Farbkombinationen führt, wenn die immer Orange ist.

**Comment by ievo** [comment]
Im contestScreen wird die Farbe der Rahmen der Gruppen noch nicht angepasst.
