### ISSUE TITLE
Logo auf Website

### ISSUE THREAD

**Issue by bespr** [bespr/SlamScoreBoard#4]
@ievo Kannst du noch das Logo (https://github.com/bespr/SlamScoreBoard/blob/master/graphics/logo-ssb.svg) auf der Website (http://bespr.github.io/SlamScoreBoard/) einbauen?

Oder ein komplett anderes Logo designen und dieses dann einbauen?

**Comment by bespr** [comment]
@ievo Cool, jedoch heisst das Bild http://bespr.github.io/SlamScoreBoard/logo_ssb.svg (Mit Underscore, nicht mit Minus), und hier ist es falsch benannt: http://bespr.github.io/SlamScoreBoard/

**Comment by ievo** [comment]
Logo ist eingebunden
