### ISSUE TITLE
Slammer Name Leerschlag

### ISSUE THREAD

**Issue by ievo** [bespr/SlamScoreBoard#7]
Leerschlag sollte möglich sein bei Eingabe des Slammer-Namens.

**Comment by ievo** [comment]
Leerschlag kann eingegeben werden ausser bei erstmaliger Eingabe des Slammer-Namens.

**Comment by bespr** [comment]
Das sollte nun eigentlich gehen.

Leerschläge werden nicht mehr bei jedem Tastaturdrücken abgeschnitten, sondern nur noch, wenn man das Feld verlässt (onblur statt onkeyup)
